Banking_System_Server: Request Class Reference
Request Class Reference abstract
The Request class is an abstract base class for handling different types of requests.
#include <Request.h>
Public Member Functions
virtual ~Request ()
Virtual destructor for the Request class.
virtual QJsonObject execute (const QJsonObject &jsonObj, QMutex &m)=0
Pure virtual method to execute a request.
Protected Member Functions
bool isDBConnectionValid (DB::DatabaseManager *dbManager)
Checks if the database connection is valid.
QJsonObject CreateDBConnectionError (QJsonObject &response, QJsonObject &dataObj)
Creates a JSON response indicating a database connection error.
QJsonObject CreateErrorResponse (QJsonObject &response, QJsonObject &dataObj, QString message)
Creates a generic error JSON response.
Detailed Description
The Request class is an abstract base class for handling different types of requests.
This class provides the common interface and utility functions for processing various requests. It includes methods for checking database connectivity and creating error responses.
Constructor & Destructor Documentation
~Request()
virtual Request::~Request () inline virtual
Virtual destructor for the Request class.
Ensures proper cleanup of derived classes.
Member Function Documentation
CreateDBConnectionError()
QJsonObject Request::CreateDBConnectionError (QJsonObject & response, QJsonObject & dataObj) inline protected
Creates a JSON response indicating a database connection error.
This method constructs a JSON response object with a status of false and a message indicating an internal server error related to database connectivity.
Parameters
response A reference to the QJsonObject that will be populated with the error response.
dataObj A reference to the QJsonObject that contains additional data about the error.
Returns
The updated QJsonObject containing the error response.
Referenced by CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), and UserInitRequest::execute().
CreateErrorResponse()
QJsonObject Request::CreateErrorResponse (QJsonObject & response, QJsonObject & dataObj, QString message) inline protected
Creates a generic error JSON response.
This method constructs a JSON response object with a status of false and a custom error message.
Parameters
response A reference to the QJsonObject that will be populated with the error response.
dataObj A reference to the QJsonObject that contains additional data about the error.
message A QString containing the error message to include in the response.
Returns
The updated QJsonObject containing the error response.
Referenced by CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), and UserInitRequest::execute().
execute()
virtual QJsonObject Request::execute (const QJsonObject & jsonObj, QMutex & m) pure virtual
Pure virtual method to execute a request.
This method must be implemented by derived classes to handle specific types of requests.
Parameters
jsonObj A QJsonObject containing the request data.
m A QMutex reference for thread-safe operations.
Returns
A QJsonObject containing the response data.
Implemented in CreateNewUserRequest, DeleteUserRequest, GetAccountNumberRequest, GetBalanceRequest, GetDatabaseRequest, GetTransactionsHistoryRequest, LoginRequest, MakeTransactionRequest, UpdateEmailRequest, UpdatePasswordRequest, UpdateUserRequest, and UserInitRequest.
isDBConnectionValid()
bool Request::isDBConnectionValid (DB::DatabaseManager * dbManager) inline protected
Checks if the database connection is valid.
This method verifies that the database connection manager is not null and that the database is properly connected. Logs error messages if the connection fails.
Parameters
dbManager A pointer to the DB::DatabaseManager instance used for checking the connection.
Returns
True if the database connection is valid, false otherwise.
Referenced by CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), and UserInitRequest::execute().
The documentation for this class was generated from the following file:
Request.h