Banking_System_Server: DB::DatabaseManager Class Reference
DB::DatabaseManager Class Reference
Manages database connections and SQL operations.
#include <db.h>
Public Member Functions
~DatabaseManager ()
Destructor for DatabaseManager.
DatabaseManager * reset ()
Resets the query settings.
DatabaseManager * select (const QString &value)
Selects columns for the query.
DatabaseManager * table (const QString &value)
Sets the table for the query.
DatabaseManager * where (const QString &value, const QVariant &val=QVariant())
Adds a WHERE clause to the query.
DatabaseManager * like (const QString &value, const QString &val)
Adds a LIKE clause to the query.
DatabaseManager * likePost (const QString &value, const QString &val)
Adds a LIKE clause with a postfix wildcard to the query.
DatabaseManager * likeNative (const QString &value, const QString &val)
Adds a native LIKE clause to the query.
DatabaseManager * whereOr (const QString &value)
Adds an OR condition to the WHERE clause.
DatabaseManager * join (const QString &value)
Adds a JOIN clause to the query.
DatabaseManager * limit (int limit)
Adds a LIMIT clause to the query.
DatabaseManager * start (int start)
Adds an OFFSET clause to the query.
DatabaseManager * sort (const QString &sort)
Adds an ORDER BY clause to the query.
DatabaseManager * group (const QString &group)
Adds a GROUP BY clause to the query.
QString getSelectQuery (const QString &select=QString())
Gets the SQL SELECT query.
QSqlError lastError ()
Gets the last error occurred.
QVariant lastInsertedId ()
Gets the ID of the last inserted record.
QString lastQuery ()
Gets the last executed query.
DbResult exec ()
Executes the built query.
DbResult execResult (const QString &sql)
Executes a SQL query.
DbResult get (const QString &tableName)
Executes a SELECT query on a specified table.
bool exec (const QString &sqlcommand)
Executes a SQL command.
bool insert (const QString &table, const QVariantMap &data)
Inserts data into a specified table.
bool update (const QString &table, const QVariantMap &data)
Updates data in a specified table.
bool del (const QString &table)
Deletes data from a specified table.
int count ()
Gets the count of records matching the query criteria.
DatabaseManager * clone ()
Clones the current DatabaseManager instance.
bool beginTransaction ()
Begins a transaction.
bool commit ()
Commits a transaction.
bool rollback ()
Rolls back a transaction.
bool isSupportTransaction ()
Checks if transactions are supported.
DatabaseManager * clearSelect ()
Clears the SELECT clause.
bool truncateTable (const QString &table)
Truncates a specified table.
Static Public Member Functions
static DatabaseManager * createInstance (bool checkDBName=false, bool newConnection=false, QString *err=nullptr)
Creates an instance of DatabaseManager.
static bool setDbSetting (const QString &host, int port, const QString &username, const QString &password, const QString &dbname)
Sets the database settings.
static bool checkConnection (QString &error)
Checks the database connection.
Detailed Description
Manages database connections and SQL operations.
This class provides methods for managing database connections, executing SQL queries, and handling transactions.
Member Function Documentation
beginTransaction()
bool DatabaseManager::beginTransaction ()
Begins a transaction.
Returns
True if the transaction started successfully, false otherwise.
checkConnection()
bool DatabaseManager::checkConnection (QString & error) static
Checks the database connection.
Parameters
error Reference to store error message.
Returns
True if connection is successful, false otherwise.
Referenced by Request::isDBConnectionValid().
clearSelect()
DatabaseManager* DB::DatabaseManager::clearSelect () inline
Clears the SELECT clause.
Returns
Pointer to the DatabaseManager instance.
clone()
DatabaseManager * DatabaseManager::clone ()
Clones the current DatabaseManager instance.
Returns
Pointer to the cloned DatabaseManager instance.
Referenced by count().
commit()
bool DatabaseManager::commit ()
Commits a transaction.
Returns
True if the transaction was committed successfully, false otherwise.
count()
int DatabaseManager::count ()
Gets the count of records matching the query criteria.
Returns
Count of records.
createInstance()
DatabaseManager * DatabaseManager::createInstance (bool checkDBName = false, bool newConnection = false, QString * err = nullptr) static
Creates an instance of DatabaseManager.
Parameters
checkDBName Flag to check database name.
newConnection Flag to create a new connection.
err Pointer to store error message.
Returns
Pointer to DatabaseManager instance.
Referenced by checkConnection().
del()
bool DatabaseManager::del (const QString & table)
Deletes data from a specified table.
Parameters
table Name of the table.
Returns
True if the data was deleted successfully, false otherwise.
Referenced by DeleteUserRequest::execute(), and UpdateUserRequest::execute().
exec() [1/2]
DbResult DatabaseManager::exec ()
Executes the built query.
Returns
DbResult object containing the result of the query.
Referenced by CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), UserInitRequest::execute(), get(), and truncateTable().
exec() [2/2]
bool DatabaseManager::exec (const QString & sqlcommand)
Executes a SQL command.
Parameters
sqlcommand SQL command to execute.
Returns
True if the command executed successfully, false otherwise.
execResult()
DbResult DatabaseManager::execResult (const QString & sql)
Executes a SQL query.
Parameters
sql SQL query to execute.
Returns
DbResult object containing the result of the query.
get()
DbResult DatabaseManager::get (const QString & tableName)
Executes a SELECT query on a specified table.
Parameters
tableName Name of the table.
Returns
DbResult object containing the result of the query.
getSelectQuery()
QString DatabaseManager::getSelectQuery (const QString & select = QString())
Gets the SQL SELECT query.
Parameters
select Optional select clause.
Returns
SQL SELECT query as a string.
Referenced by count(), and exec().
group()
DatabaseManager * DatabaseManager::group (const QString & group)
Adds a GROUP BY clause to the query.
Parameters
group Grouping criteria.
Returns
Pointer to the DatabaseManager instance.
insert()
bool DatabaseManager::insert (const QString & table, const QVariantMap & data)
Inserts data into a specified table.
Parameters
table Name of the table.
data Data to insert.
Returns
True if the data was inserted successfully, false otherwise.
Referenced by CreateNewUserRequest::execute(), and MakeTransactionRequest::execute().
isSupportTransaction()
bool DB::DatabaseManager::isSupportTransaction () inline
Checks if transactions are supported.
Returns
True if transactions are supported, false otherwise.
join()
DatabaseManager * DatabaseManager::join (const QString & value)
Adds a JOIN clause to the query.
Parameters
value JOIN clause.
Returns
Pointer to the DatabaseManager instance.
Referenced by GetAccountNumberRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), and MakeTransactionRequest::execute().
lastError()
QSqlError DatabaseManager::lastError ()
Gets the last error occurred.
Returns
QSqlError object containing the last error.
Referenced by createInstance().
lastInsertedId()
QVariant DatabaseManager::lastInsertedId ()
Gets the ID of the last inserted record.
Returns
ID of the last inserted record.
lastQuery()
QString DatabaseManager::lastQuery ()
Gets the last executed query.
Returns
Last executed query as a string.
Referenced by exec().
like()
DatabaseManager * DatabaseManager::like (const QString & value, const QString & val)
Adds a LIKE clause to the query.
Parameters
value Column name.
val Value for the LIKE clause.
Returns
Pointer to the DatabaseManager instance.
likeNative()
DatabaseManager * DatabaseManager::likeNative (const QString & value, const QString & val)
Adds a native LIKE clause to the query.
Parameters
value Column name.
val Value for the LIKE clause.
Returns
Pointer to the DatabaseManager instance.
likePost()
DatabaseManager * DatabaseManager::likePost (const QString & value, const QString & val)
Adds a LIKE clause with a postfix wildcard to the query.
Parameters
value Column name.
val Value for the LIKE clause.
Returns
Pointer to the DatabaseManager instance.
limit()
DatabaseManager * DatabaseManager::limit (int limit)
Adds a LIMIT clause to the query.
Parameters
limit Number of records to limit.
Returns
Pointer to the DatabaseManager instance.
reset()
DatabaseManager * DatabaseManager::reset ()
Resets the query settings.
Returns
Pointer to the DatabaseManager instance.
Referenced by del(), exec(), execResult(), insert(), and update().
rollback()
bool DatabaseManager::rollback ()
Rolls back a transaction.
Returns
True if the transaction was rolled back successfully, false otherwise.
select()
DatabaseManager * DatabaseManager::select (const QString & value)
Selects columns for the query.
Parameters
value Columns to select.
Returns
Pointer to the DatabaseManager instance.
Referenced by CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), UserInitRequest::execute(), and getSelectQuery().
setDbSetting()
bool DatabaseManager::setDbSetting (const QString & host, int port, const QString & username, const QString & password, const QString & dbname) static
Sets the database settings.
Parameters
host Database host.
port Database port.
username Database username.
password Database password.
dbname Database name.
Returns
True if settings are set successfully, false otherwise.
sort()
DatabaseManager * DatabaseManager::sort (const QString & sort)
Adds an ORDER BY clause to the query.
Parameters
sort Sorting criteria.
Returns
Pointer to the DatabaseManager instance.
start()
DatabaseManager * DatabaseManager::start (int start)
Adds an OFFSET clause to the query.
Parameters
start Offset value.
Returns
Pointer to the DatabaseManager instance.
table()
DatabaseManager * DatabaseManager::table (const QString & value)
Sets the table for the query.
Parameters
value Table name.
Returns
Pointer to the DatabaseManager instance.
Referenced by del(), CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), UserInitRequest::execute(), get(), insert(), truncateTable(), and update().
truncateTable()
bool DatabaseManager::truncateTable (const QString & table)
Truncates a specified table.
Parameters
table Name of the table.
Returns
True if the table was truncated successfully, false otherwise.
update()
bool DatabaseManager::update (const QString & table, const QVariantMap & data)
Updates data in a specified table.
Parameters
table Name of the table.
data Data to update.
Returns
True if the data was updated successfully, false otherwise.
Referenced by del(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), and UpdateUserRequest::execute().
where()
DatabaseManager * DatabaseManager::where (const QString & value, const QVariant & val = QVariant())
Adds a WHERE clause to the query.
Parameters
value Condition for the WHERE clause.
val Value for the condition.
Returns
Pointer to the DatabaseManager instance.
Referenced by CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), and UserInitRequest::execute().
whereOr()
DatabaseManager * DatabaseManager::whereOr (const QString & value)
Adds an OR condition to the WHERE clause.
Parameters
value Condition for the OR clause.
Returns
Pointer to the DatabaseManager instance.
Referenced by GetTransactionsHistoryRequest::execute().
The documentation for this class was generated from the following files:
db.h
db.cpp