Banking_System_Server: DB::DbResult Class Reference
DB::DbResult Class Reference
The DbResult class represents a result set returned from a database query.
#include <dbresult.h>
Public Member Functions
DbResult ()
Default constructor for DbResult.
DbResult (const QList< QVariant > &data)
Constructs a DbResult from a list of QVariant data.
bool isEmpty () const
Checks if the result set is empty.
QJsonObject first () const
Retrieves the first item in the result set.
int size () const
Gets the number of items in the result set.
QJsonObject data (int pos) const
Retrieves data at a specific position in the result set.
QJsonArray data () const
Gets all the data in the result set.
QString toJsonString () const
Converts the result set to a JSON string.
Detailed Description
The DbResult class represents a result set returned from a database query.
This class encapsulates the data returned from a database operation and provides methods to access and manipulate the result. It stores the result in a JSON array format.
Constructor & Destructor Documentation
DbResult() [1/2]
DbResult::DbResult ()
Default constructor for DbResult.
Initializes an empty DbResult object.
DbResult() [2/2]
DbResult::DbResult (const QList< QVariant > & data)
Constructs a DbResult from a list of QVariant data.
Parameters
data A QList<QVariant> containing data to be stored in the result. The data is converted into a JSON array of QJsonObjects.
Member Function Documentation
data() [1/2]
QJsonArray DbResult::data () const
Gets all the data in the result set.
Returns
A QJsonArray containing all the items in the result set.
Referenced by DbResult(), and first().
data() [2/2]
QJsonObject DbResult::data (int pos) const
Retrieves data at a specific position in the result set.
Parameters
pos The index position of the item to retrieve.
Returns
A QJsonObject representing the data at the specified position. Returns an empty QJsonObject if the position is out of bounds or if the result set is empty.
Referenced by GetDatabaseRequest::execute(), and GetTransactionsHistoryRequest::execute().
first()
QJsonObject DbResult::first () const
Retrieves the first item in the result set.
Returns
A QJsonObject representing the first item. If the result set is empty, returns an empty QJsonObject.
Referenced by CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), and UserInitRequest::execute().
isEmpty()
bool DbResult::isEmpty () const
Checks if the result set is empty.
Returns
True if the result set is empty, false otherwise.
Referenced by data(), CreateNewUserRequest::execute(), DeleteUserRequest::execute(), GetAccountNumberRequest::execute(), GetBalanceRequest::execute(), GetDatabaseRequest::execute(), GetTransactionsHistoryRequest::execute(), LoginRequest::execute(), MakeTransactionRequest::execute(), UpdateEmailRequest::execute(), UpdatePasswordRequest::execute(), UpdateUserRequest::execute(), and UserInitRequest::execute().
size()
int DbResult::size () const
Gets the number of items in the result set.
Returns
The number of items in the result set.
Referenced by data(), GetDatabaseRequest::execute(), and GetTransactionsHistoryRequest::execute().
toJsonString()
QString DbResult::toJsonString () const
Converts the result set to a JSON string.
Returns
A QString containing the JSON representation of the result set.
The documentation for this class was generated from the following files:
dbresult.h
dbresult.cpp