@startuml Request Sequence Diagram
actor "ServerHandler" as SH
participant "RequestManager" as RM
participant "QJsonDocument" as JsonDoc
participant "QJsonParseError" as JsonError
participant "Request" as Req

SH -> RM: makeRequest(data)
activate RM
RM -> JsonDoc: fromJson(data)
alt JSON parse error
    RM -> SH: handleJsonParseError(parseError)
else JSON parse succeeded
    JsonDoc -> RM: return jsonObjRequest
    RM -> RM: parse request number
    alt request not found
        RM -> SH: log "Request not found"
    else request found
        RM -> Req: execute(jsonObjRequest, Mutex)
        activate Req
        Req -> RM: return response
        RM -> SH: return responseByteArr
        deactivate Req
    end
end
deactivate RM
@enduml