name: Documentation
on:
  push:
    tags:
      - "*"
    branches: [ main, master ]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        make dependency

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.7.1'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: 'qtconnectivity qthttpserver qtmultimedia qtnetworkauth qtremoteobjects qtscxml'
        tools: 'tools_ninja'

    - name: prepare
      run: |
        make clean

    - name: clean configure
      run: |
        make clean-cache-reconfigure

    - name: building
      run: |
        make build

    - name: Documentation generation
      run: |
        make html

    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: 7osssam@protonmail.ch
        build_dir: ./docs/doxygen/html