name: Ubuntu CI Test

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]


jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        make dependency

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.7.1'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        modules: 'qtconnectivity qthttpserver qtmultimedia qtnetworkauth qtremoteobjects qtscxml'
        tools: 'tools_ninja'

    - name: cleaning up
      run: |
        make clean

    - name: building
      run: |
        make build-debug

    - name: testing
      run: |
        make test